### ISSUE TITLE
Error when contact has no emails

### ISSUE THREAD

**Issue by seiferteric** [Diego81/omnicontacts#127]
I get the following when importing a contact that has no emails associated with it.

```
NoMethodError (undefined method `[]' for nil:NilClass):
  omnicontacts (0.3.5) lib/omnicontacts/importer/gmail.rb:91:in `block in contacts_from_response'
  omnicontacts (0.3.5) lib/omnicontacts/importer/gmail.rb:51:in `each'
  omnicontacts (0.3.5) lib/omnicontacts/importer/gmail.rb:51:in `contacts_from_response'
  omnicontacts (0.3.5) lib/omnicontacts/importer/gmail.rb:27:in `fetch_contacts_using_access_token'
  omnicontacts (0.3.5) lib/omnicontacts/middleware/oauth2.rb:53:in `fetch_contacts'
  omnicontacts (0.3.5) lib/omnicontacts/middleware/base_oauth.rb:66:in `block in handle_callback'
  omnicontacts (0.3.5) lib/omnicontacts/middleware/base_oauth.rb:80:in `execute_and_rescue_exceptions'
  omnicontacts (0.3.5) lib/omnicontacts/middleware/base_oauth.rb:62:in `handle_callback'
  omnicontacts (0.3.5) lib/omnicontacts/middleware/base_oauth.rb:39:in `call'
  omnicontacts (0.3.5) lib/omnicontacts/builder.rb:27:in `call'
  warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.3) lib/warden/manager.rb:34:in `catch'
  warden (1.2.3) lib/warden/manager.rb:34:in `call'
  rack (1.6.0) lib/rack/etag.rb:24:in `call'
  rack (1.6.0) lib/rack/conditionalget.rb:25:in `call'
  rack (1.6.0) lib/rack/head.rb:13:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.0) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.0) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:88:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:88:in `_run_callbacks'
  activesupport (4.2.0) lib/active_support/callbacks.rb:734:in `_run_call_callbacks'
  activesupport (4.2.0) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.0) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.0) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.0) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.0) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.0) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.0) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.0) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.0) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.0) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.0) lib/rails/engine.rb:518:in `call'
  railties (4.2.0) lib/rails/application.rb:164:in `call'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:74:in `process_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:455:in `block (3 levels) in start_threads'
```

The error on line 91 of gmail.rb is when trying to use `contact[:emails][0][:email]` since there is no email `contact[:emails][0]` is nil, so you get the error. I will try to send a pull request.

**Comment by seiferteric** [comment]
Ahh, I just noticed after I cloned that there appears to be a fix in there already on line 92, just not in my installed version 0.3.5. I will try installing from github and test again.

**Comment by seiferteric** [comment]
Ya, its fixed.

**Comment by jagdishbhanderi** [comment]
I am getting same error. My installed version is 0.3.5. 
Please help me. Its urgent.

**Comment by rubytastic** [comment]
Use github repo instead of published gem.
Where are you using it? We might can take a look

**Comment by seiferteric** [comment]
@jagdishbhanderi Just use this in your Gemfile instead:

    gem 'omnicontacts', git: 'https://github.com/Diego81/omnicontacts.git'

**Comment by jagdishbhanderi** [comment]
Thank you. Problem is solved by using github repo.

**Comment by anguyen-elc** [comment]
Hi guys, is it resolved? I have the same problem but don't know I can use the same method. Please advise. Many thanks.
